apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: 
  namespace: 
  labels:
    app: -app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: -app
  template:
    metadata:
      labels:
        app: -app
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: registry.citizenscience.ch/
        ports:
        - containerPort: 
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: -service
  namespace: 
spec:
  selector:
    app: -app
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: -ingress
  namespace: 
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/configuration-snippet: |
    #  more_set_headers "server: hide";
    #  more_set_headers "X-Content-Type-Options: nosniff";
    #  more_set_headers "X-Frame-Options: DENY";
    #  more_set_headers "X-Xss-Protection: 1";
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - 
    - www.
    secretName: tls-certificate-secret
  rules:
  - host: 
    http:
      paths:
      - path: "/"
        backend:
          serviceName: -service
          servicePort: http
  - host: www.
    http:
      paths:
      - path: "/"
        backend:
          serviceName: -service
          servicePort: http
